apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hello-world-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    iam:
      withAddonPolicies:
        awsLoadBalancerController: true
        externalDNS: true
        certManager: true
        ebs: true
